# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


Vagrant.configure(2) do |config|
	config.vm.provision "docker"

	config.vm.provision "shell", inline:
		"ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

	config.vm.define "docker-host"

	config.vm.box = "ubuntu/trusty64"

	config.vm.network "forwarded_port", guest: 8080, host: 8080
	config.vm.network "forwarded_port", guest: 49161, host: 49161

	config.vm.provider :virtualbox do |vb|
   		vb.name = "docker-host"
      	vb.memory = 3500
        vb.cpus = 2
		vb.gui = true
		#Osäker om det här löser något just nu.. behövde det innan.
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   	end




#	config.vm.provision "shell", inline:<<-SHELL

	
#	SHELL

	


end
